-
   description: General Chair for ACL 2017
-
   description: Program Co-Chair for EMNLP 2015
-
   description: Secretary-Treasurer for SIGDAT 2016-present
-
   description: Past Chair of the NAACL Executive Board 2014-2015
-
   description: Chair of the NAACL Executive Board 2012-2013
-
   description: Board Member for NAACL Executive Board 2010-2011
-
   description: Action Editor for Transactions of the Association for Computational Linguistics 2012-2016
-
   description: Editorial Board for Computational Linguistics 2010-2012
-
   description: Executive Committee, Institute for Research in Cognitive Science (IRCS), University of Pennsylvania 2013-2016
-
   description: Advisory Board, Human Language Technology Center of Excellence (HLTCOE), Johns Hopkins University 2016-present
-
   description: Board Member for American Machine Translation Association 2009-2010
-
   description: North American Representative for ACL Special Interest Group in Machine Translation 2009-2010 
-
   description: Area Chair for Generation and Summarization for NAACL 2015
-
   description: Area Chair for Machine Translation for EMNLP 2014
-
   description: Area Chair for Machine Translation for CoLing 2010
-
   description: Area Chair for Machine Translation for EACL 2009
-
   description: Co-Organizer of the NAACL 2010  Workshop on Creating Language Data With Mechanical Turk
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2013 (102+ participants) 
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2012 (90 participants)  
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2011 (133 participants)  
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2010 
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2009 (approximately 125+ participants) 
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2008 (148 participants) 
-
   description: Co-Organizer of the Workshop on Statistical Machine Translation 2007 (117 participants) 
-
   description: Co-Organizer of the ACL 2009 Textual Entailment Workshop (30 participants) 
-
   description: Co-Organizer of the Machine Translation Marathon 2010 (approximately 100 participants) 
-
   description: Co-Organizer of the Machine Translation Marathon 2009 (approximately 80 participants) 
-
   description: Co-Organizer of the Machine Translation Marathon 2008 (approximately 70 participants) 
-
   description: Co-Organizer of the Machine Translation Marathon 2007 (approximately 50 participants) 
-
   description: Co-Chair of ACL 2005 Student Research Workshop
-
   description: Steering Committee for ACL 2011 Workshop on Monolingual Text-To-Text Generation 
-
   description: Chair of Diversity Committee, JHU Computer Science Department
-
   description: Graduate Admissions Committee, JHU Computer Science Department
-
   description: Chair of Website Re-Design and Video Archiving Committee, CLSP
-
   description: Program Committee Member for EMNLP 2016
-
   description: Program Committee Member for NAACL 2016
-
   description: Program Committee Member for ACL 2014
-
   description: Program Committee Member for CoLing 2014
-
   description: Reviewer for CSCW 2014
-
   description: Program Committee Member for ACL 2013
-
   description: Program Committee Member for NAACL 2013
-
   description: Program Committee Member for CoNLL 2013
-
   description: Program Committee Member for CHI 2013
-
   description: Program Committee Member for NAACL 2012
-
   description: Program Committee Member for AMTA 2012
-
   description: Program Committee Member for ACL 2012
-
   description: Program Committee Member for EACL 2012
-
   description: Program Committee Member for EMNLP 2011
-
   description: Program Committee Member for ACL 2011
-
   description: Program Committee Member for HCOMP 2011
-
   description: Program Committee Member for AAAI 2010
-
   description: Program Committee Member for ACL 2010
-
   description: Program Committee Member for NAACL 2010
-
   description: Program Committee Member for EMNLP 2009
-
   description: Program Committee Member for NAACL 2009
-
   description: Program Committee Member for EAMT 2009
-
   description: Program Committee Member for MT Summit 2009
-
   description: Program Committee Member for AMTA 2008
-
   description: Program Committee Member for CoLing 2008
-
   description: Program Committee Member for ACL 2008
-
   description: Program Committee Member for EMNLP 2008
-
   description: Program Committee Member for ACL 2007
-
   description: Program Committee Member for IJCNLP 2007
-
   description: Program Committee Member for ACL 2006
-
   description: Program Committee Member for ACL 2006 Student Research Workshop
-
   description: Program Committee Member for AMTA 2006
-
   description: Program Committee Member for IJCAI 2006
-
   description: Program Committee Member for EMNLP 2006
-
   description: Reviewer for Journal of Computational Linguistics
-
   description: Reviewer for Journal of Transactions of the Association for Computational Linguistics
-
   description: Reviewer for Journal of Natural Language Engineering
-
   description: Reviewer for Journal of Machine Translation
-
   description: Reviewer for Journal of Artificial Intelligence Research
-
   description: Reviewer for Journal of Linguistic Issues in Language Technology